### ISSUE TITLE
Create java class Customer

### ISSUE THREAD

**Issue by ZhectorSM** [ZhectorSM/MovieTheatre#12]
Create a java class of the entity Customer with its properties using encapsulation and override the methods: hashcode, equals and toString

**Comment by HiroakiBandai** [comment]
package com.javafever.customer;

public class custormer {
 private int id_custormer;
 private String first_name;
 private String last_name;
 private String gender;
 private String email;
 private int points;
public int getId_custormer() {
	return id_custormer;
}
public void setId_custormer(int id_custormer) {
	this.id_custormer = id_custormer;
}
public String getFirst_name() {
	return first_name;
}
public void setFirst_name(String first_name) {
	this.first_name = first_name;
}
public String getLast_name() {
	return last_name;
}
public void setLast_name(String last_name) {
	this.last_name = last_name;
}
public String getGender() {
	return gender;
}
public void setGender(String gender) {
	this.gender = gender;
}
public String getEmail() {
	return email;
}
public void setEmail(String email) {
	this.email = email;
}
public int getPoints() {
	return points;
}
public void setPoints(int points) {
	this.points = points;
}
@Override
public int hashCode() {
	final int prime = 31;
	int result = 1;
	result = prime * result + ((email == null) ? 0 : email.hashCode());
	result = prime * result + ((first_name == null) ? 0 : first_name.hashCode());
	result = prime * result + ((gender == null) ? 0 : gender.hashCode());
	result = prime * result + id_custormer;
	result = prime * result + ((last_name == null) ? 0 : last_name.hashCode());
	result = prime * result + points;
	return result;
}
@Override
public boolean equals(Object obj) {
	if (this == obj)
		return true;
	if (obj == null)
		return false;
	if (getClass() != obj.getClass())
		return false;
	custormer other = (custormer) obj;
	if (email == null) {
		if (other.email != null)
			return false;
	} else if (!email.equals(other.email))
		return false;
	if (first_name == null) {
		if (other.first_name != null)
			return false;
	} else if (!first_name.equals(other.first_name))
		return false;
	if (gender == null) {
		if (other.gender != null)
			return false;
	} else if (!gender.equals(other.gender))
		return false;
	if (id_custormer != other.id_custormer)
		return false;
	if (last_name == null) {
		if (other.last_name != null)
			return false;
	} else if (!last_name.equals(other.last_name))
		return false;
	if (points != other.points)
		return false;
	return true;
}
@Override
public String toString() {
	return "custormer [id_custormer=" + id_custormer + ", first_name=" + first_name + ", last_name=" + last_name
			+ ", gender=" + gender + ", email=" + email + ", points=" + points + "]";
}
 
 
}
