### ISSUE TITLE
Create script for movie table

### ISSUE THREAD

**Issue by ZhectorSM** [ZhectorSM/MovieTheatre#2]
Create the SQL script for the movie table of the model #1

**Comment by jcrf15** [comment]
create database movie3;
create table loyal_programs (
id_loyal_program int primary key auto_increment not null,
discount float not null,
minimum_points int not null
);
create table locations(
id_location int primary key auto_increment not null,
location varchar (50),
address varchar (50)

);
create table customers (
 id_customer int primary key auto_increment not null,
 first_name varchar (50) not null,
 last_name varchar (50) not null,
 gender varchar (1) not null,
 email varchar (50) null,
 points int
 
 
 );
 create table category (
id_category int primary key auto_increment not null,
name1 varchar (50) not null
);

create table movie (
id_movie int primary key auto_increment not null,
name1 varchar(50) not null,
id_category int not null,
director varchar (50) not null,
actor varchar (50) not null,
year1 varchar (50) not null,
runtime varchar (50) not null,
rate varchar (50) not null,
FOREIGN KEY (id_category) REFERENCES category(id_category)

);
 create table auditorium (
 id_auditorium int primary key auto_increment not null,
 seat_total varchar (50) not null,
 vip boolean not null,
 id_location int not null,
 FOREIGN KEY (id_location) REFERENCES locations(id_location)
 );
 create table schedule1 (
id_schedule int primary key auto_increment not null,
showtime datetime not null,
id_auditorium int not null,
id_movie int not null,
price float not null,
seat int not null,
FOREIGN KEY (id_movie) REFERENCES movie(id_movie),
FOREIGN KEY (id_auditorium) REFERENCES auditorium(id_auditorium)
);

create table ticket (
id_ticket int primary key auto_increment not null,
id_loyal_program float not null,
id_customer int not null,
id_schedule int not null,
FOREIGN KEY (id_schedule) REFERENCES schedule1(id_schedule),
FOREIGN KEY (id_customer) REFERENCES customers(id_customer)
);
