### ISSUE TITLE
Create script for Auditorium table

### ISSUE THREAD

**Issue by ZhectorSM** [ZhectorSM/MovieTheatre#6]
Create script for Auditorium table for the database

**Comment by sachiko0811** [comment]
CREATE table auditorium(
id_auditorium int PRIMARY KEY AUTO_INCREMENT,
seat_total VARCHAR(50) NOT NULL,
vip boolean NOT NULL,
id_location int NOT NULL,
FOREIGN KEY (id_location) REFERENCES locations(id_location)
);
